"use client"
import * as React from 'react';

export default function HomeV2() {
  return (
    <main>
      <div className="w-full h-full my-10 mx-10">
        <h1 className="font-bold text-xl">Stock App V2</h1>
        <p>Generated by create next app</p>
      </div>
    </main>
  );
}